### ISSUE TITLE
Installation error on Python 3.8.1

### ISSUE THREAD

**Issue by fjsj** [dedupeio/dedupe#787]
Hi folks, I'm getting the following error when trying to `pip install dedupe` on Python 3.8.1:

```
Collecting dedupe-hcluster
  Downloading https://files.pythonhosted.org/packages/66/d1/4d04530d130a6a99e1d335a36065736ecbfbc6dd145b46414d7326a248a5/dedupe-hcluster-0.3.6.tar.gz (201kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpasc356lx
       cwd: /tmp/pip-install-m1v03h08/dedupe-hcluster
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-w63n4esj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-w63n4esj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-w63n4esj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 236, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-w63n4esj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpasc356lx Check the logs for full command output.
```

Even when I try to install numpy, I still get the same error. Full installation steps in [this Gist](https://gist.github.com/fjsj/31ea05e5d02e4948293cc3b2f8c922fe).

Got the same error on Mac OS Mojave 10.14.6 (18G2022) and on Debian (thru Docker python:3.8.1-buster).

**Comment by fgregg** [comment]
this should be addressed by this change in fastcluster https://github.com/dmuellner/fastcluster/pull/13

**Comment by fjsj** [comment]
@fgregg thanks for the response.

New `fastcluster` version has been launched, but `pip install -U dedupe` is still failing for me.

Additionally, when I try "Developing dedupe" README setup instructions, I get the same error on `pip install -e .`.

Finally, when trying `python setup.py install` instead, I get the following error. If I try a couple times more `setup.py install`, it eventually works:

```
Installed /Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/dedupe_hcluster-0.3.6-py3.8-macosx-10.14-x86_64.egg
Searching for fastcluster
Reading https://pypi.org/simple/fastcluster/
Downloading https://files.pythonhosted.org/packages/a5/1f/8de0150716634a49fe4b0bf7fe2282dba35fbafed7b2cd3cc3b4078283ec/fastcluster-1.1.26.tar.gz#sha256=a202f44a3b06f5cf9cdba3c67d6c523288922d6e6a1cdf737292f93759aa82f7
Best match: fastcluster 1.1.26
Processing fastcluster-1.1.26.tar.gz
Writing /var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-hqf1ls3m/fastcluster-1.1.26/setup.cfg
Running fastcluster-1.1.26/setup.py -q bdist_egg --dist-dir /var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-hqf1ls3m/fastcluster-1.1.26/egg-dist-tmp-lhs6hpyi
Traceback (most recent call last):
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-hqf1ls3m/fastcluster-1.1.26/setup.py", line 12, in <module>
    'categorical-distance>=1.9',
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/core/overrides.py", line 16, in <module>
    add_docstring(
RuntimeError: implement_array_function method already has a docstring

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    setup(
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/fjsj/.pyenv/versions/3.8.1/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/fjsj/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/fjsj/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 751, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
    dist = best[req.key] = env.best_match(
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/fjsj/.pyenv/versions/3.8.1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/fjsj/.pyenv/versions/3.8.1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-hqf1ls3m/fastcluster-1.1.26/setup.py", line 12, in <module>
    'categorical-distance>=1.9',
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/fjsj/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/numpy/core/overrides.py", line 16, in <module>
    add_docstring(
RuntimeError: implement_array_function method already has a docstring
```

Above the error happened at `fastcluster` installation. Then it happens at `pyhacrf-datamade`, and `PyLBFGS`. After the third time running `python setup.py install`, it works. Seems you can't import numpy several times during the same installation, as per https://github.com/numpy/numpy/issues/14012

**Comment by fjsj** [comment]
Note, the error above happens due to `numpy>=1.16`.

If you do the same w/ `numpy>=1.13,<1.16`, you get another error:
```
Installed /Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/persistent-4.5.1-py3.8-macosx-10.14-x86_64.egg
Searching for pyhacrf-datamade>=0.2.0
Reading https://pypi.org/simple/pyhacrf-datamade/
Downloading https://files.pythonhosted.org/packages/a0/86/d407bd9e8541c2d7e9fc0d9344a35a6be1a02c7ba65ef4d4b6ea7afc6f33/pyhacrf-datamade-0.2.3.tar.gz#sha256=88517957abd7484835da23ff06085cdce34c5818e0bca90e42f8be093b347239
Best match: pyhacrf-datamade 0.2.3
Processing pyhacrf-datamade-0.2.3.tar.gz
Writing /var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-xq7otq91/pyhacrf-datamade-0.2.3/setup.cfg
Running pyhacrf-datamade-0.2.3/setup.py -q bdist_egg --dist-dir /var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-xq7otq91/pyhacrf-datamade-0.2.3/egg-dist-tmp-2q1owjl5
Compiling pyhacrf/algorithms.pyx because it depends on /Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
Compiling pyhacrf/adjacent.pyx because it depends on /Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
[1/2] Cythonizing pyhacrf/adjacent.pyx
/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-xq7otq91/pyhacrf-datamade-0.2.3/pyhacrf/adjacent.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2215, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions
    self.stats = [stat.analyse_expressions(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>
    self.stats = [stat.analyse_expressions(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 6675, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 12999, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-xq7otq91/pyhacrf-datamade-0.2.3/setup.py", line 12, in <module>
    'categorical-distance>=1.9',
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1202, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1597, in __call__
    return super_class.__call__(root)
  File "Cython/Compiler/Visitor.py", line 355, in Cython.Compiler.Visitor.EnvTransform.__call__
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1607, in visit_ModuleNode
    node.analyse_declarations(self.current_env())
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 124, in analyse_declarations
    self.body.analyse_declarations(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 7913, in analyse_declarations
    module_scope = env.find_module(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Symtab.py", line 1269, in find_module
    return module_scope.context.find_module(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 232, in find_module
    err, result = self.process_pxd(source_desc, scope, qualified_name)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 146, in process_pxd
    result = Pipeline.run_pipeline(pipeline, source_desc)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2210, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...
    if PyDataType_HASSUBARRAY(d):
        return <tuple>d.subarray.shape
    else:
        return ()

cdef inline char* _util_dtypestring(dtype descr, char* f, char* end, int* offset) except NULL:
    ^
------------------------------------------------------------

/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd:842:5: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(__init__.pxd:17:0)
StatListNode.stats[41] = StatListNode(__init__.pxd:842:5)
StatListNode.stats[0] = CFuncDefNode(__init__.pxd:842:5,
    args = [...]/4,
    inline_in_pxd = True,
    modifiers = [...]/1,
    visibility = 'private')

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2215, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions
    self.stats = [stat.analyse_expressions(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>
    self.stats = [stat.analyse_expressions(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 6675, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 12999, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    setup(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 751, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
    dist = best[req.key] = env.best_match(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/user/.pyenv/versions/3.8.1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/nw/s6lx123n073bp6_2r0vz9zcw0000gp/T/easy_install-xq7otq91/pyhacrf-datamade-0.2.3/setup.py", line 12, in <module>
    'categorical-distance>=1.9',
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1202, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1597, in __call__
    return super_class.__call__(root)
  File "Cython/Compiler/Visitor.py", line 355, in Cython.Compiler.Visitor.EnvTransform.__call__
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1607, in visit_ModuleNode
    node.analyse_declarations(self.current_env())
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 124, in analyse_declarations
    self.body.analyse_declarations(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 431, in analyse_declarations
    stat.analyse_declarations(env)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 7913, in analyse_declarations
    module_scope = env.find_module(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Symtab.py", line 1269, in find_module
    return module_scope.context.find_module(
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 232, in find_module
    err, result = self.process_pxd(source_desc, scope, qualified_name)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 146, in process_pxd
    result = Pipeline.run_pipeline(pipeline, source_desc)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2210, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd>, 842, 5), 'AnalyseExpressionsTransform', 'Compiler crash in AnalyseExpressionsTransform\n\nModuleNode.body = StatListNode(__init__.pxd:17:0)\nStatListNode.stats[41] = StatListNode(__init__.pxd:842:5)\nStatListNode.stats[0] = CFuncDefNode(__init__.pxd:842:5,\n    args = [...]/4,\n    inline_in_pxd = True,\n    modifiers = [...]/1,\n    visibility = \'private\')\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2215, in visit_FuncDefNode\n    node.body = node.body.analyse_expressions(node.local_scope)\n  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions\n    self.stats = [stat.analyse_expressions(env)\n  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>\n    self.stats = [stat.analyse_expressions(env)\n  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 6675, in analyse_expressions\n    self.item = self.item.coerce_to(self.target.type, env)\n  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to\n    src = PyTypeTestNode(src, dst_type, env)\n  File "/Users/user/workspace/dedupe-3.8.1/venv/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 12999, in __init__\n    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"\nAssertionError: PyTypeTest on non extension type', AssertionError('PyTypeTest on non extension type'), <traceback object at 0x115092cc0>)
```

Exact reproduction steps:
```
pip install "numpy>=1.13,<1.16"  # changed
pip install -r requirements.txt
cython src/*.pyx
python setup.py install  # changed
```

**Comment by fgregg** [comment]
this has been fixed on master, and a new version is availabe on pypi https://pypi.org/project/dedupe/
