### ISSUE TITLE
KeyError in DedupeSample._sample method

### ISSUE THREAD

**Issue by imp-sh** [dedupeio/dedupe#945]
Environment:
Python 3.9.10
dudupe 2.0.10

When dedupe is generating its sample, the random_sample_keys generated overflow the data array.

The size of the data set going in is 395,236 rows with samplesize=15000 passed to prepare_training. 

```
Traceback:

Preparing to run training.
Traceback (most recent call last):
  File "D:\...\example.py", line 178, in <module>
    linker.prepare_training(temp_m, sample_size=15000)
  File "D:\...\venv\lib\site-packages\dedupe\api.py", line 1274, in prepare_training
    self._sample(data, sample_size, blocked_proportion)
  File "D:\...\venv\lib\site-packages\dedupe\api.py", line 1300, in _sample
    self.active_learner = self.ActiveLearner(self.data_model,
  File "D:\...\venv\lib\site-packages\dedupe\labeler.py", line 421, in __init__
    self.candidates = self._sample(data, blocked_proportion, sample_size)
  File "D:\...\venv\lib\site-packages\dedupe\labeler.py", line 59, in _sample
    return [(data[k1], data[k2])
  File "D:\...\venv\lib\site-packages\dedupe\labeler.py", line 59, in <listcomp>
    return [(data[k1], data[k2])
KeyError: 49392508508
```

Values going into the list comprehension in DedupeSampler:

```
        return [(data[k1], data[k2])
                for k1, k2
                in blocked_sample_keys | random_sample_keys]

blocked_sample_keys = {set}  
 {tuple} (67459, 242709)
 {tuple} (10886, 99148)
 {tuple} (194215, 210979)
....

random_sample_keys = {set}  
 {tuple} (325702, 75162282879)
 {tuple} (186740, 55834957394)
 {tuple} (84098, 30065137414)
....

.0 = {set_iterator} <set_iterator object at 0x000001A71ACDD600>
data = {dict}  
k1 = {int32} 84098
k2 = {int64} 30065137414
```

**Comment by fgregg** [comment]
probably introduced by https://github.com/dedupeio/dedupe/commit/6c59172ecdec634d7a56ae039c18616cc14cf39b#diff-2cf2fb7f867feffafbfe66a5b8e8822da70738406dd3b85a28c83892da6e50a5

**Comment by FakieKickflip** [comment]
Ran in the same error with just 

`df_final = pandas_dedupe.dedupe_dataframe(df,['first_name', 'last_name'])`

on a windows machine, python 3.7.7 and pandas-dedupe==1.5.0.

My data set is over 500.000 rows

**Comment by fgregg** [comment]
should be addressed by 7317798104aa9303d4f0f4bcece35e6e6a15e424

**Comment by imp-sh** [comment]
I'm still having this issue in a new 3.9.10 venv, Dedupe 2.11.0 running dudupe-examples/mysql_example.py & demo data. I can't think of anything else client-side that it would be. 

In randomPairs, the n-value is still extremely large. The total length of the data array for this example is only 706025

```
random_sample_size = {int} 150
blocked_proportion = {float} 0.9
blocked_sample_keys = {set}  
blocked_sample_size = {int} 1350
data = {deque}  
predicates = {list}  
random_sample_size = {int} 150
sample_size = {int} 1500
self = {DedupeDisagreementLearner}  
...
n = {int} 249235297300
n_records = {int} 706025
sample_size = {int} 150
```

   
```
Traceback (most recent call last):
  File "C:\Users\impsh\PycharmProjects\dedupe-examples\mysql_example\mysql_example.py", line 147, in <module>
    deduper.prepare_training(temp_d)
  File "C:\Users\impsh\PycharmProjects\dedupe-examples\venv\lib\site-packages\dedupe\api.py", line 1274, in prepare_training
    self._sample(data, sample_size, blocked_proportion)
  File "C:\Users\impsh\PycharmProjects\dedupe-examples\venv\lib\site-packages\dedupe\api.py", line 1300, in _sample
    self.active_learner = self.ActiveLearner(self.data_model,
  File "C:\Users\impsh\PycharmProjects\dedupe-examples\venv\lib\site-packages\dedupe\labeler.py", line 421, in __init__
    self.candidates = self._sample(data, blocked_proportion, sample_size)
  File "C:\Users\impsh\PycharmProjects\dedupe-examples\venv\lib\site-packages\dedupe\labeler.py", line 59, in _sample
    return [(data[k1], data[k2])
  File "C:\Users\impsh\PycharmProjects\dedupe-examples\venv\lib\site-packages\dedupe\labeler.py", line 59, in <listcomp>
    return [(data[k1], data[k2])
KeyError: 6442846455
```

**Comment by fgregg** [comment]
how annoying, @imp-sh.

could you possibly write a test case for randomPairsMatch that fails on windows?

https://github.com/dedupeio/dedupe/blob/master/tests/test_core.py#L26

**Comment by ibrottier** [comment]
Hey everyone,

I'm also having the same issue, KeyError when running the dedupe_dataframe funcition. I've also trained with older versions of the library and the problem persists

> Traceback (most recent call last):
  File "C:/Users/ignacio.brottier/Documents/PROJECTOS/DEDUPE/New_vendor_dedupe/new_vendor_dedupe.py", line 218, in <module>
    df_final = dupe_train(df_data)
  File "C:/Users/ignacio.brottier/Documents/PROJECTOS/DEDUPE/New_vendor_dedupe/new_vendor_dedupe.py", line 72, in dupe_train
    df_train = pandas_dedupe.dedupe_dataframe(df_sample, columns_list)
  File "C:\Users\ignacio.brottier\AppData\Roaming\Python\Python37\site-packages\pandas_dedupe\dedupe_dataframe.py", line 242, in dedupe_dataframe
    sample_size, update_model)
  File "C:\Users\ignacio.brottier\AppData\Roaming\Python\Python37\site-packages\pandas_dedupe\dedupe_dataframe.py", line 105, in _train
    deduper = _active_learning(data, sample_size, deduper, training_file, settings_file)
  File "C:\Users\ignacio.brottier\AppData\Roaming\Python\Python37\site-packages\pandas_dedupe\dedupe_dataframe.py", line 41, in _active_learning
    deduper.prepare_training(data, sample_size=sample_num)
  File "C:\Users\ignacio.brottier\AppData\Local\Programs\Python\Python37\lib\site-packages\dedupe\api.py", line 1274, in prepare_training
    self._sample(data, sample_size, blocked_proportion)
  File "C:\Users\ignacio.brottier\AppData\Local\Programs\Python\Python37\lib\site-packages\dedupe\api.py", line 1304, in _sample
    index_include=examples)
  File "C:\Users\ignacio.brottier\AppData\Local\Programs\Python\Python37\lib\site-packages\dedupe\labeler.py", line 421, in __init__
    self.candidates = self._sample(data, blocked_proportion, sample_size)
  File "C:\Users\ignacio.brottier\AppData\Local\Programs\Python\Python37\lib\site-packages\dedupe\labeler.py", line 61, in _sample
    in blocked_sample_keys | random_sample_keys]
  File "C:\Users\ignacio.brottier\AppData\Local\Programs\Python\Python37\lib\site-packages\dedupe\labeler.py", line 60, in <listcomp>
    for k1, k2
KeyError: 4295081543

Process finished with exit code 1
